name: C/C++ CI docker

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  jana2_env_everything_except_cuda:
    name: Build JANA2 with all dependencies except CUDA
    runs-on: ubuntu-latest
    container:
      image: nbrei/jana2_env_everything_except_cuda
    
    # Build Docker container and run the entrypoint.sh script in it
    steps:

    - uses: actions/checkout@v4

    - name: build
      run: |
        cmake -S . -B build -DCMAKE_INSTALL_PREFIX=`pwd` \
          -DUSE_PYTHON=ON \
          -DUSE_ROOT=ON \
          -DUSE_PODIO=ON \
          -DUSE_XERCES=ON \
          -DUSE_ZEROMQ=ON \
          -DXercesC_DIR=/usr \
          -Dpodio_DIR=/app/podio/install/lib/cmake/podio/
        cmake --build build --target install
    - name: JTest
      run: |
        echo "--- Running JTest plugin -----------------------"
        $GITHUB_WORKSPACE/bin/jana -PPLUGINS=JTest -Pjana:nevents=100
    - name: jana-unit-tests
      run: |
        echo "--- Running jana-unit-tests ------------------------------"
        export LD_LIBRARY_PATH=$GITHUB_WORKSPACE/lib/JANA/plugins:$LD_LIBRARY_PATH
        $GITHUB_WORKSPACE/bin/jana-unit-tests
    - name: TimesliceExample with simple (physics event) topology
      run: |
        echo "--- Running TimesliceExample with simple topology ------------------------------"
        export LD_LIBRARY_PATH=$GITHUB_WORKSPACE/lib/JANA/plugins:/app/podio/install/lib:$LD_LIBRARY_PATH
        $GITHUB_WORKSPACE/bin/jana -Pplugins=TimesliceExample -Pjana:nevents=100 events.root
    - name: TimesliceExample with complex (timeslice) topology
      run: |
        echo "--- Running TimesliceExample with complex topology ------------------------------"
        export LD_LIBRARY_PATH=$GITHUB_WORKSPACE/lib/JANA/plugins:/app/podio/install/lib:$LD_LIBRARY_PATH
        $GITHUB_WORKSPACE/bin/jana -Pplugins=TimesliceExample -Pjana:nevents=100 timeslices.root


