name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-18.04
    
    steps:
    - uses: actions/checkout@v2
    - name: cmake
      run: |
        mkdir build
        cd build
        cmake ../ -DCMAKE_INSTALL_PREFIX=$GITHUB_WORKSPACE/Linux
    - name: make
      run: |
        pwd
        echo "----- ls ------"
        ls
        echo "----- ls .. ------"
        ls ..
        echo "----- ls $GITHUB_WORKSPACE/ ------"
        ls $GITHUB_WORKSPACE/
        make $GITHUB_WORKSPACE/build
    - name: make install
      run: make install
