name: C/C++ CI docker

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  jana2_env_everything_except_cuda:
    name: Build JANA2 with all dependencies except CUDA
    runs-on: ubuntu-latest
    container:
      image: nbrei/jana2_env_everything_except_cuda
    steps:
    - uses: actions/checkout@v4
    - name: build
      run: |
        cmake -S . -B build -DCMAKE_INSTALL_PREFIX=`pwd` \
          -DUSE_PYTHON=ON \
          -DUSE_ROOT=ON \
          -DUSE_PODIO=ON \
          -DUSE_XERCES=ON \
          -DUSE_ZEROMQ=ON \
          -DXercesC_DIR=/usr \
          -Dpodio_DIR=/app/podio/install/lib/cmake/podio/
        cmake --build build --target install
    - name: Examine dynamic linking
      run: |
        echo "ldd bin/jana"
        ldd bin/jana
        echo "ldd bin/libJANA.so"
        ldd lib/libJANA.so
        echo "bin/jana rpath"
        objdump -x bin/jana | grep PATH
        echo "lib/libJANA.so rpath"
        objdump -x lib/libJANA.so | grep PATH
        echo "lib/JANA/plugins/TimesliceExample.so"
        objdump -x lib/JANA/plugins/TimesliceExample.so | grep PATH
        echo "bin/PodioExample"
        objdump -x bin/PodioExample | grep PATH
    - name: JTest
      run: |
        ctest --test-dir build --output-on-failure -R jana-plugin-jtest-tests
    - name: jana-unit-tests
      run: |
        ctest --test-dir build --output-on-failure -R jana-unit-tests
    - name: TimesliceExample with simple (physics event) topology
      run: |
        ctest --test-dir build --output-on-failure -R jana-example-timeslices-simple-tests
    - name: TimesliceExample with complex (timeslice) topology
      run: |
        ctest --test-dir build --output-on-failure -R jana-example-timeslices-complex-tests


