name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-18.04
    
    # Run cmake, make, and make install as separate steps
    # Note that every step starts out in the $GITHUB_WORKSPACE
    # directory.
    steps:
    - uses: actions/checkout@v2
    - name: cmake
      run: |
        mkdir -p $GITHUB_WORKSPACE/build
        cd $GITHUB_WORKSPACE/build
        cmake ../ -DCMAKE_INSTALL_PREFIX=$GITHUB_WORKSPACE/Linux -DJANA_HOME=$GITHUB_WORKSPACE/Linux
    - name: make
      run: |
        cd $GITHUB_WORKSPACE/build
        make
    - name: make install
      run: |
        cd $GITHUB_WORKSPACE/build
        cat cmake_install.cmake
        make install
