name: C/C++ CI docker

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  jana2_env_everything_except_cuda:
    name: Build JANA2 with all dependencies except CUDA
    runs-on: ubuntu-latest
    container:
      image: nbrei/jana2_env_everything_except_cuda
    steps:
    - uses: actions/checkout@v4
    - name: build
      run: |
        cmake -S . -B build -DCMAKE_INSTALL_PREFIX=`pwd` \
          -DUSE_PYTHON=ON \
          -DUSE_ROOT=ON \
          -DUSE_PODIO=ON \
          -DUSE_XERCES=ON \
          -DUSE_ZEROMQ=ON \
          -DXercesC_DIR=/usr \
          -Dpodio_DIR=/app/podio/install/lib/cmake/podio/
        cmake --build build --target install
    - name: JTest
      run: |
        echo "--- Running JTest plugin -----------------------"
        ctest --test-dir build -R jana-plugin-jtest-tests --rerun-failed --output-on-failure
    - name: jana-unit-tests
      run: |
        echo "--- Running jana-unit-tests ------------------------------"
        ctest --test-dir build -R jana-unit-tests --rerun-failed --output-on-failure
    - name: TimesliceExample with simple (physics event) topology
      run: |
        echo "--- Running TimesliceExample with simple topology ------------------------------"
        ctest --test-dir build -R jana-example-timeslices-simple-tests --rerun-failed --output-on-failure
    - name: TimesliceExample with complex (timeslice) topology
      run: |
        echo "--- Running TimesliceExample with complex topology ------------------------------"
        ctest --test-dir build -R jana-example-timeslices-simple-tests --rerun-failed --output-on-failure


