name: C/C++ CI ubuntu

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    strategy:
      matrix:
        os: [ubuntu-18.04, ubuntu-20.04, ubuntu-22.04]

    # See https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on for available platforms
    runs-on: ${{ matrix.os }}

    # Run cmake, make, and make install as separate steps
    # Note that every step starts out in the $GITHUB_WORKSPACE
    # directory.
    steps:
    - uses: actions/checkout@v2
    - name: cmake
      run: |
        mkdir -p $GITHUB_WORKSPACE/build
        cd $GITHUB_WORKSPACE/build
        cmake ../ -DCMAKE_INSTALL_PREFIX=$GITHUB_WORKSPACE/Linux -DUSE_ROOT=Off
    - name: make
      run: |
        cd $GITHUB_WORKSPACE/build
        make
    - name: make install
      run: |
        cd $GITHUB_WORKSPACE/build
        make install
    - name: run tests
      run: |
        export JANA_PLUGIN_PATH=$GITHUB_WORKSPACE/Linux/plugins
        echo "--- Running JTest plugin -----------------------"
        $GITHUB_WORKSPACE/Linux/bin/jana -PPLUGINS=JTest -Pjana:nevents=100
        echo "--- Running janatests ------------------------------"
        $GITHUB_WORKSPACE/Linux/bin/janatests

