name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-18.04
    
    steps:
    - uses: actions/checkout@v2
    - name: cmake
      run: |
        mkdir build
        cd build
        cmake ../JANA2 -DCMAKE_INSTALL_PREFIX=$GITHUB_WORKSPACE/Linux
    - name: make
      run: make
    - name: make install
      run: make install
